---
title: "Links"
---

# Regional Forecast Discussions

* [NWS-Sacramento Forecast Discussion](https://forecast.weather.gov/product.php?site=STO&issuedby=STO&product=AFD&format=CI&version=1&glossary=1) (Sacramento Valley and west slope northern Sierras)
* [NWS-Reno Forecast Discussion](https://forecast.weather.gov/product.php?site=REV&issuedby=REV&product=AFD&format=CI&version=1&glossary=1) (Sierra crest, eastern slope northern Sierras, and western Nevada)
* Northern California Geogrpahic Coordination Center [7-day Outlook](https://gacc.nifc.gov/oncc/predictive/weather/7Day.pdf)

# Weather Models

* Use [metoblue](https://www.meteoblue.com/en/weather/forecast/multimodelensemble/forest-ranch_united-states_5349956) to compare forecasts from different weather models.
* [Tropical Tidbits](https://www.tropicaltidbits.com/analysis/models/?model=gfs&region=wus&pkg=apcpn&runtime=2022101118&fh=6) offers dozens of parameters from the main models.
* [Pivotal Weather](https://www.pivotalweather.com/model.php?p=sfcrh) is very similar to tropical tidbits, with some better functionality for comparing models and exporting images.

# Blogs
* Danial Swain, a.k.a. [Weather West](weatherwest.com), periodically writes a blog about macro-scale weather phenomena impacting California and the west, often providing relevant context for wildfire and drought concerns. 

# Imagery

* GOES-17 Satellite imagery from [College of DuPage](https://weather.cod.edu/satrad/?parms=local-N_California-truecolor-24-1-100-1&checked=map&colorbar=undefined)
